### ISSUE TITLE
Grimrail + Iron Docks not filtering out unlootable items after updating

### ISSUE THREAD

**Issue by Rittler281** [teelolws/ShadowlandsSeason4EncounterJournal#8]
Grimrail Depot and Iron Docks are not allowing filtering of class, shows every item the dungeon drops for all classes/specs. As a Hunter I am seeing cloth, leather, plate and intellect items. Only these two dungeons remove the options to filter by class/spec.

**Comment by teelolws** [comment]
Yeah I know. The Mythic 0 list provided by the game is completely wrong, so I replaced it with the list from https://www.wowhead.com/news/list-of-currently-confirmed-loot-drops-from-season-4-mythic-grimrail-depot-iron-328237

Theres no way to check if an item is *optimal* for your class/spec. Best I was able to do was check for Red Text on the item, which is why you won't see Plate items as a hunter.

You say you're seeing Plate but I just checked on a Hunter character and don't see Plate.

**Comment by wyz-0801** [comment]
something wrong with loot list，deamon hunter cant see weapons

**Comment by teelolws** [comment]
Probably cause that article doesn't have any loot for Demon Hunters. Do you know what weapons drop there for DH?

**Comment by premoe** [comment]
I'm having the same issue as Rittler, on both my rogue and DK. 
the items that show up are all wrong and the drop down menus to change class and difficulty etc are missing. 
only happends on GD and ID

**Comment by teelolws** [comment]
I can't allow class/spec filtering for Grimrail or Iron Docks as Blizzard doesn't give me any functions to ask "does this item drop for this class?".

**Comment by premoe** [comment]
> I can't allow class/spec filtering for Grimrail or Iron Docks as Blizzard doesn't give me any functions to ask "does this item drop for this class?".

oo i see, thanks for clearing that up!
